### ISSUE TITLE
Add 'Launch on system startup' menu item 

### ISSUE THREAD

**Issue by jariz** [jariz/Noti#10]

**Comment by jariz** [comment]
Postponed: fixes have higher priority

**Comment by m0n9oose** [comment]
Are you sure you want to implement this feature?

Mac OS already have ability to set up list of applications which should start at boot

<img width="479" alt="screen shot 2016-07-28 at 19 17 12" src="https://cloud.githubusercontent.com/assets/1478556/17212188/544d6a8e-5500-11e6-9e64-653eb5e371dd.png">

**Comment by m0n9oose** [comment]
By the way, thanks a lot for nice and free application! Great job!

**Comment by jariz** [comment]
Yes, but this would simplify it. It would work through the same interface. 
(i.e. when you enable it, it will be added to the 'Login items' list in Users & Groups).

**Comment by jariz** [comment]
0.2 is released.
