### ISSUE TITLE
iOS support?

### ISSUE THREAD

**Issue by lordgiotto** [jariz/Noti#15]
Hi, do you plan to support iOS notifications as well as Android's ones? :)

**Comment by jariz** [comment]
As far as I know, [PushBullet does not support this at the moment](https://www.reddit.com/r/PushBullet/comments/3y5qaz/is_there_a_way_to_get_pushbullet_notifications_on/), stating Apple's restrictive API's. So until PushBullet does, I'm afraid this won't be an option for Noti either.

**Comment by lordgiotto** [comment]
Ok, I understand, thank you very much :)
