### ISSUE TITLE
Crash when showing notification with actions on a non-pro account

### ISSUE THREAD

**Issue by shaggyb50** [jariz/Noti#17]
I have been trying to test Noti by setting a Google Keep note to be a notification, but when my phone buzzes the Noti menubar element disappears. Was able to get text and test notis from Pushbullet. I was almost certain Google Keep would work because it was a notification featured on the app website.

**Comment by jariz** [comment]
Hey, I've not been able to reproduce this behavior myself.  
Can you:  

1. Open your terminal (Terminal.app)
2. Execute `/Applications/Noti.app/Contents/MacOS/Noti`  
3. Reproduce issue
4. Comment with the full output on this issue.

**Comment by shaggyb50** [comment]
StatusMenuController alive
Encryption not enabled
Getting user info...
"{\"active\":true,\"iden\":\"ujEGIeNgoVM\",\"created\":1.46945845713093e+09,\"modified\":1.469540474385896e+09,\"email\":\"nvboettcher@gmail.com\",\"email_normalized\":\"nvboettcher@gmail.com\",\"name\":\"Bryan Boettcher\",\"image_url\":\"https://static.pushbullet.com/google-user/ea3bbcba7a45dc44dcd36ef748f35c1b96241c3fba2ad62cb64ec3bb4dd03163\",\"max_upload_size\":26214400}"
PushManager receive {"type": "nop"}
Unknown type of message  Optional("nop")
PushManager Is connected
PushManager receive {"type": "nop"}
Unknown type of message  Optional("nop")
PushManager receive {"type": "nop"}
Unknown type of message  Optional("nop")
PushManager receive {"type": "nop"}
Unknown type of message  Optional("nop")
PushManager receive {"type": "nop"}
Unknown type of message  Optional("nop")
PushManager receive {"type": "nop"}
Unknown type of message  Optional("nop")
PushManager receive {"type": "nop"}
Unknown type of message  Optional("nop")
PushManager receive {"type": "nop"}
Unknown type of message  Optional("nop")
PushManager receive {"type": "nop"}
Unknown type of message  Optional("nop")
PushManager receive {"type": "nop"}
Unknown type of message  Optional("nop")
PushManager receive {"type": "nop"}
Unknown type of message  Optional("nop")

**Comment by shaggyb50** [comment]
No Encryption, no PB pro.

**Comment by jariz** [comment]
Oh, yup. It crashes when a notification (with actions) comes in and the user doesn't have pro.

**Comment by jariz** [comment]
A new version has just been released that fixes this issue, Click 'check for updates' in the Noti menu, Thanks for reporting.

**Comment by shaggyb50** [comment]
Your app was auto update by Macupdate Desktop. I was getting notis all day
at work, which was perfect because I left my phone at home! Thanks

Bryan
