### ISSUE TITLE
Messages received through the API won't get displayed

### ISSUE THREAD

**Issue by evdtempel** [jariz/Noti#21]
Bug/enhancement:
Messages received through the API won't get displayed. If I get a notification through the API, I do get it on my phone and in the browser, but not through Noti.

**Comment by drobati** [comment]
Yeah, I've noticed this too. If you have a suggestion on how to debug the app, I can provide some testing.

**Comment by jariz** [comment]
Noti was designed to just show Android notifications, but this would be a good addition, I agree.

**Comment by jariz** [comment]
Development is done, will be released when `0.3` is out in the coming week.
