### ISSUE TITLE
Settings screen

### ISSUE THREAD

**Issue by jariz** [jariz/Noti#27]
Considering there are a lot of feature requests regarding settings, it's probably best to add a settings screen as well while implementing these.  
This would contain:
- #19 Notification sound setting
- #10 Start with system option
- #26 Omit app name setting
- PushBullet password could also be moved into here with a bit of a better UI that clearly indicates whether it's enabled or not (it's kinda vague right now)
- Thumbnail rounding on/off

**Comment by mirshko** [comment]
@jariz Here is my take at the updated settings panel with all the settings marked above! 

![noti system settings panel wip](https://cloud.githubusercontent.com/assets/8116716/19545102/b134baf8-9651-11e6-8221-64d4d8eedefe.png)

**Comment by mirshko** [comment]
Here is the updated panel with the icons.

![noti system settings panel v2](https://cloud.githubusercontent.com/assets/8116716/19602173/284fe760-977a-11e6-9bea-efb291fa6d29.png)

@jariz Here is the sketch file in case you need it: [Noti System Settings.zip](https://github.com/jariz/Noti/files/544551/Noti.System.Settings.zip)

**Comment by jariz** [comment]
0.2 is released.
