### ISSUE TITLE
I suggest a change in the app and taskbar icon

### ISSUE THREAD

**Issue by mirshko** [jariz/Noti#28]
I don't have any ideas right now I just don't really feel the face (while being super cute) really fits what the app does.

**Comment by jariz** [comment]
It's my design, I gave it my best shot.
If anyone wants to contribute with a new icon, I'll be happy to take a look at it.

**Comment by mirshko** [comment]
I wouldn't mind helping! :D

**Comment by mirshko** [comment]
I've got a couple ideas now.

**Comment by mirshko** [comment]
<img width="548" alt="screen shot 2016-10-04 at 10 29 26 am" src="https://cloud.githubusercontent.com/assets/8116716/19078233/713d88b6-8a1d-11e6-9013-0892aed6d49c.png">

Just an idea!

**Comment by mirshko** [comment]
I was thinking to use different faces to show different actions needed on the icon. Such as `Failed account linkage` or `no actions needed (no notifications)`

<img width="1043" alt="screen shot 2016-10-04 at 10 33 29 am" src="https://cloud.githubusercontent.com/assets/8116716/19078406/01a19e06-8a1e-11e6-92ce-9275aa54773f.png">

**Comment by mirshko** [comment]
@jariz What do you think?

**Comment by jariz** [comment]
Wow! This is awesome! I love them!
It indeed does fit the purpose of the app much more.

However, 'action needed' would be kinda hard to implement sadly.
Because, there's no way of telling if a user is caught up: for example, you could've seen the notification, but you didn't dismiss it, it's annoying to then have the icon still wanting your attention.
There's also no notification history, so we'd have to create a whole UI to show the notifications you might have missed, which is cool and something I'd consider higher priority than #23, but maybe a bit outside of the scope.

Which of the 3 would you consider best for the default state? I kind of prefer the last one, but that's probably because it looks most like the old icon 😛

**Comment by mirshko** [comment]
I also like the right most one! :D Its the most friendly (also it has the same joyous feeling of the old one)

What format do you need the icons in? I can export anything (made them in Sketch)

Also for the main image with the gradient on it I'm working on something for that as well right now!

**Comment by jariz** [comment]
The sketch project file would be fine, as I have sketch myself too.
Either upload it somewhere or email it to me, jarizw@gmail.com
Thanks!
Yea, the app icon desperately needs change too. (#25)
Keep in mind that it needs to work with multicolored backgrounds.

**Comment by markrjr** [comment]
I'm not really a graphic designer, but when I need logos for my project I always check out IconFinder.

https://www.iconfinder.com/search/?q=notification&license=1&price=free

All of those are free for commercial use.

**Comment by mirshko** [comment]
@markrjr So we have a new logo to use. I was asking for a screenshot of how bad the old logo looked for you so I have something to go by.

**Comment by mirshko** [comment]
<img width="167" alt="screen shot 2016-10-04 at 3 42 33 pm" src="https://cloud.githubusercontent.com/assets/8116716/19089637/2ea3435c-8a49-11e6-8d34-2ea774baf622.png">

Here is the old one with macOS Sierra

**Comment by markrjr** [comment]
Oh. http://imgur.com/a/lHPpk

**Comment by mirshko** [comment]
Cool cool, Ill work on a solid-colored one for the main product icon!

**Comment by mirshko** [comment]
<img width="761" alt="screen shot 2016-10-04 at 8 39 21 pm" src="https://cloud.githubusercontent.com/assets/8116716/19097419/a9679b6e-8a72-11e6-8b09-b8a666ea89cc.png">

How's something like this for the icon? The white is solid not transparent. Its hard to come up with a good color for this icon. I would say pushbullet green but thats probably not okay to use.

**Comment by mirshko** [comment]
<img width="508" alt="screen shot 2016-10-04 at 8 44 18 pm" src="https://cloud.githubusercontent.com/assets/8116716/19097513/5dd2f094-8a73-11e6-9810-6b7b5feb385c.png">

Might look something like this in the notification center.

**Comment by jariz** [comment]
**App icon:**

The problem with that is that it has to work on multi colored backgrounds. If the user has dark mode enabled for example, it'll look this: (see if you can spot it)

![2222](https://cloud.githubusercontent.com/assets/1415847/19107774/21ea2e46-8aee-11e6-8d49-d15bdf688fab.png)

I propose something like this:

![artboard copy](https://cloud.githubusercontent.com/assets/1415847/19108712/21448780-8af2-11e6-9281-f3b76ec9c8c7.png)

would work a lot better.

**Sketch file:**

Great, thanks, but could you also include the 'account_link_failure' one?
I can use that one for connection errors and stuff.

**Comment by mirshko** [comment]
Ahh I see! Alright I'll try with a rounded icon!

In the meantime, the updated **Sketch file**: [Noti Menu Bar Icons V2 - Jeff Reiner.zip](https://github.com/jariz/Noti/files/511347/Noti.Menu.Bar.Icons.V2.-.Jeff.Reiner.zip)

**Comment by jariz** [comment]
0.2 is released.
