### ISSUE TITLE
How about a homebrew cask?

### ISSUE THREAD

**Issue by halr9000** [jariz/Noti#29]
I'd love to install Noti this way:
`brew cask install noti`

How about an official pacakge? https://caskroom.github.io/

If not interested, LMK, maybe I'll bottle one up that points at your DMG.

Contrib instructions over there: https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md

**Comment by halr9000** [comment]
Here's a working cask. It fails audit says some things are out of order, but I don't have time to figure out why that would be.

noti.rb:
`cask 'noti' do
  version '0.1.4'
  sha256 '6836e1f26a67be8ab96ec09fb612b07dae823722b78f59214a64e8d3aa11c26a'

  # github.com/jariz/Noti was verified as official when first introduced to the cask
  url "https://github.com/jariz/Noti/releases/download/#{version}/Noti.dmg"
  name 'Noti'
  homepage 'https://noti.center/'
  license :oss
  app 'Noti.app'
  appcast 'https://github.com/jariz/Noti/releases.atom',
    checkpoint: '5fd70f1dea5ac15a20247c96e9c16a7a3153f35623a93ac6ba59eb72bdb40f51'
end
`

**Comment by halr9000** [comment]
Always wanted an excuse to go through that process. :)

**Comment by jariz** [comment]
Hey, I'll look into this today. Not sure why I forgot to add it to cask, thanks.

**Comment by jariz** [comment]
PR has been filed.
caskroom/homebrew-cask#25429

**Comment by jariz** [comment]
PR was merged.
