### ISSUE TITLE
Replying to messages via NC spams all your friends

### ISSUE THREAD

**Issue by macfeaster** [jariz/Noti#30]
Hi,

Not sure how else to phrase this... 😅
I'm using Noti on 10.10.5 and it mostly works great. Excerpt for one thing!

Whenever I reply using the notification center bubble reply action to any Facebook Messenger message, Noti sends my reply some 15 times to the person I talk to. It then proceeds to spam some 5-6 random friends of mine with the same message an arbitrary number of times over the next minute.

Using the latest Noti (0.1.4) on 10.10.5 with Android 6.0.1 and latest Pushbullet app. I have no idea what else information I could provide, so please ask for logs or anything that could help in resolving this. 😄

**Comment by jariz** [comment]
Yea, this is a known fixed problem (#22) which will be included in the next update.  
However, I think I'm gonna push a hotfix release to fix this as it's a pretty big problem which makes quick reply fairly useless (and the next update might take at least a month to complete).  
I'll keep this issue open until the update's released.

**Comment by macfeaster** [comment]
Oh, sorry! I checked past issues but I missed that one. Hotfix would be fantastic! Especially if the next update will take a while. That way you don't have to rush the update :) great app otherwise, thanks!

**Comment by jariz** [comment]
[0.1.5 has been released.](https://github.com/jariz/Noti/releases/tag/0.1.5)
