### ISSUE TITLE
Generally not working

### ISSUE THREAD

**Issue by FranciscoAmado** [jariz/Noti#33]
Hi,
I've installed Noti last night. Since then, I've received several notifications on my phone, while being on my Mac with Noti enabled, and none of them did come up on the Mac.
I also have Pushbullet installed on my phone and it was working correctly through the Chrome Extension.

Just for the record, I've an Asus Zenphone 2.

Thanks for Noti, it seems amazing :)
Francisco

**EDIT**

I've downloaded and debugged it. Seems that everything is fine with the session, my data is correct but no notifications are received

**Comment by jariz** [comment]
Hi Francisco,
I'm not sure what to do with this, maybe you used a different account on the extension than on Noti?
It's happened to me before.
I doubt this a problem with the program though.

**Comment by FranciscoAmado** [comment]
I was commenting again that nothing came up and a Notification poped... I'll close it xD Thanks!
