### ISSUE TITLE
Clicking on the notification opens many, many tabs

### ISSUE THREAD

**Issue by iparr** [jariz/Noti#36]
When a notification slides into view to tell me that I have a notification message, clicking on it will start to open many (50+?) tabs in Chrome (my default browser) and I have to start frantically trying to close them all before my computer slows to a crawl.

Can the behaviour be modified to open just one tab or - even better - take no action at all?

I have learnt to never click on a Noti notification - but I often forget this mistake!

I'm on Noti 0.1.5 and El Capitan Version 10.11.6. Thanks for the app.

**Comment by jariz** [comment]
That shouldn't happen. Let me see if I can reproduce this.

**Comment by jariz** [comment]
Out of curiousity, why do you want it to take no action at all?

**Comment by iparr** [comment]
Im sorry, to be clear it would great if the app knew which website to open, but if that isn't possible then it'd be best if it didn't do anything.

Worth me saying: At the moment when I click a notification from my Reddit app it is clever enough to open reddit.com which is great, it just does this as well as very many copies of Hangouts.

I don't expect you'll be able to know from every app what the most relevant website is - maybe you will! I'm no Android dev.

**Comment by jariz** [comment]
Yes, it already determines which app matches which website, but obviously it should open just that website, not other notifications.
I'll get on this asap.

**Comment by iparr** [comment]
This seems to be a great improvement. Thank you for your efforts.
