### ISSUE TITLE
Settings gear icon on Peferences panel is lighter than rest of icons for headers

### ISSUE THREAD

**Issue by mirshko** [jariz/Noti#37]
The gear icon is lighter than the rest of the Noti and encryption icons! 

See attached screenshot. 

![screen shot 2016-12-27 at 9 25 42 am](https://cloud.githubusercontent.com/assets/8116716/21501527/a4ded748-cc16-11e6-9654-8be559802ccd.png)

**Comment by jariz** [comment]
Will be fixed once `0.3` is released in the coming week.
