### ISSUE TITLE
Selected 'Notification Sound' in Preferences is ignored

### ISSUE THREAD

**Issue by sebj** [jariz/Noti#38]
No matter which Notification Sound I choose in Noti's preferences, the default 'Glass' sound is used.

Edit: Could be down to a mistake on [Line` 394` of `PushManager.swift`](https://github.com/jariz/Noti/blob/master/Noti/PushManager.swift#L394) (`forKey: "sound"` not `forKey: "roundedImages"`)

**Comment by jariz** [comment]
NIcely spotted, that probably is the issue.  
For now, enable & disable the rounded images option, then 😛

**Comment by sebj** [comment]
Haha 😅

**Comment by jariz** [comment]
Will be fixed once `0.3` is released in the coming week.
