### ISSUE TITLE
Noti does not show a notification for incoming calls

### ISSUE THREAD

**Issue by blaichch** [jariz/Noti#39]
It only shows a notification for missed calls, but not for incoming calls. I guess that's because the Phone app shows a fullscreen notification instead of a normal notification. Is there a way to implement a notification for incoming calls?

Device: Nexus 5X
OS: Android 7.1.1
Phone App: Phone 7.4.141193972

**Comment by jariz** [comment]
I can swear I've seen notifications before... maybe this is something they changed?  
I don't get calls that often so I'm not really sure.  
Eitherway, this sounds more like an PushBullet issue to me, all Noti does is just display what it gets from PB.

**Comment by jariz** [comment]
An annoying recruiter called me today (thanks recruiter!) so I can definitely confirm that it works.  
![screen shot 2017-01-10 at 17 02 13](https://cloud.githubusercontent.com/assets/1415847/21813657/3afa89d4-d757-11e6-80cc-7bf2ab026f14.png)
