### ISSUE TITLE
Extend Notifications time on screen

### ISSUE THREAD

**Issue by FranciscoAmado** [jariz/Noti#41]
Heya!

I sometimes struggle with clicking on notifications due to their short time on screen.

I took a look into your *Info.plist* and you're setting `NSUserNotificationAlertStyle` as `banner` which is fine! But, if you change it to `alert`, the notifications stick around a little more I believe.

I think this would be more convenient.

Thanks for Noti! I would miss most of my messages if not for it xD

**Comment by jariz** [comment]
While developing the application, I had the notifications as alert by default, but I ended up with a lot of notifications clogging my screen, so I figured banner would be a better default.  
Eitherway, it doesn't matter all that much, as you can change the setting on an application basis through the system notification settings and the value in the Info.plist is just a default value.

**Comment by FranciscoAmado** [comment]
Fair enough xD
Thanks for the feedback
