### ISSUE TITLE
"brew cask install noti" not working :/

### ISSUE THREAD

**Issue by sameerkumar18** [jariz/Noti#48]
I tried "brew cask install noti"
but it shows the following error 
"""
Warning: The default Caskroom location has moved to /usr/local/Caskroom.

Please migrate your Casks to the new location and delete /opt/homebrew-cask/Caskroom,
or if you would like to keep your Caskroom at /opt/homebrew-cask/Caskroom, add the
following to your HOMEBREW_CASK_OPTS:

  --caskroom=/opt/homebrew-cask/Caskroom

For more details on each of those options, see https://github.com/caskroom/homebrew-cask/issues/21913.
Error: No available Cask for noti. Did you mean one of:
feedbinnotifier		   gmail-notifr		      growlnotify		 spotify-notifications
gmail-notifier		   google-notifier	      notifyr			 stack-exchange-notifier

Error: nothing to install
"""
Thanks :)

**Comment by jariz** [comment]
Judging by the warning message, I'm guessing you've installed brew a while
ago. Can you try running `brew update` ?

**Comment by sameerkumar18** [comment]
Thanks!
That worked 👍
