### ISSUE TITLE
Yosemite compatibility dropped?

### ISSUE THREAD

**Issue by SilverEzhik** [jariz/Noti#51]
Seems that the latest update does not support Yosemite. Despite that the built-in update function updated to that release and broke itself...

**Comment by jariz** [comment]
I'm fairly sure it should function fine on Yosemite, but you can always download an older version from the releases page:  
https://github.com/jariz/Noti/releases

**Comment by SilverEzhik** [comment]
Yeah, I downgraded for now, but the latest build seems to be incompatible:
![Disk image](https://cloud.githubusercontent.com/assets/4080683/23581871/a5e21c04-00d2-11e7-984e-6c4a54745061.png)
![Error](https://cloud.githubusercontent.com/assets/4080683/23581873/ab89e524-00d2-11e7-85fd-40bfe56afcb9.png)

**Comment by FoxxMD** [comment]
Any update on this?

**Comment by jariz** [comment]
One of our dependencies, Alamofire, does not support 10.10.
I'm marking this as 'wontfix'.
MacOS is on 10.13 by now and we'll keep the target on 10.11 for the forseeable future.
Eitherway I think you should just all update your macs, if I'm honest.
