### ISSUE TITLE
Mute notifications from some apps

### ISSUE THREAD

**Issue by cameronsstone** [jariz/Noti#58]
The windows pushbullet app has a nice feature where you can tell it to suppress notifications from a particular source. For example, I don't need to see email notifications from my phone on my desktop because I get desktop notifications.

Complete feature would include:
1. Mute option from this source button on notification (with 2nd click for confirmation)
1. Persistance of muted app list
1. Preference interface to modify the list (to unmute and remove old apps)

**Comment by ABeltramo** [comment]
Do you have a full list of apps on phone on desktop app? Because I can't see this possibility from Pushbullet API.
Maybe some screenshot will help building this feature.

**Comment by jariz** [comment]
@cameronsstone
Can't this be done from the pushbullet app on your phone already?
Besides convenience, I can't really find a motivating factor to make implementing this seem worth the amount of trouble.

**Comment by cameronsstone** [comment]
No. I suspect it's done client side. That is, the client (desktop) adds
apps one at a time when the user selects "mute notifications from this app"
from the noti notification. The noti preferences would need some way to
remove apps from that list. I agree that a list of all phone apps would be
hard, if not impossible, to obtain.

I'll get you a screenshot from my windows machine.

Thanks.

Sent from my satellite.

On Nov 22, 2017 1:25 AM, "ABeltramo" <notifications@github.com> wrote:

Do you have a full list of apps on phone on desktop app? Because I can't
see this possibility from Pushbullet API.
Maybe some screenshot will help building this feature.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jariz/Noti/issues/58#issuecomment-346292155>, or mute
the thread

**Comment by jariz** [comment]
I understood what you meant, but I was taling about this screen:

![screenshot_20171122-164231](https://user-images.githubusercontent.com/1415847/33135997-56eb16f4-cfa4-11e7-9d5b-c7f2e59b2a96.jpg)


Sure, we could implement some sort of filter on Noti's side, but as mentioned by @ABeltramo, it'll be hard if not impossible to get a list of all apps on your phone from within Noti.

**Comment by jariz** [comment]
I do not find the motivation to implement this, given it's a setting in PB as mentioned earlier. Closing.
