### ISSUE TITLE
Is this project DEAD?

### ISSUE THREAD

**Issue by ABeltramo** [jariz/Noti#59]
I @jariz I have a pull request pending. I'm a student and I know it's difficult to trust someone on the web but I have a little bit of free time and I would love to contribute to your amazing project.
If you want help I can be a contributor!

**Comment by jariz** [comment]
Hiya. I'd absolutely love you to join the project, I just figured that after chrome's native notifications update, there wouldn't be all that much interest in Noti.
My priorities have kind of shifted too, but I still have a lot of love for the project and will help out with the occasional pull request.

I can't really remember why I didn't merge your PR already, if you can check if it still compiles fine etc you can merge it yourself (just added you as a collaborator).
We can discuss if we'd immediately release a new version or not.
Before we'd move on with anything we'll likely want to migrate the project to Swift 4 though.

Can you send me your email - either here or send me an email @ jarizw@gmail.com - so I can add you to a slack so we can have a bit of a shorter line of communication?

**Comment by jariz** [comment]
Can you confirm if #50 is still an issue? Because that seems kind of important too 🙈
