### ISSUE TITLE
Option to show notifications permanently until dismissed

### ISSUE THREAD

**Issue by pztrn** [jariz/Noti#64]
When SMS is received I can't manage to read it, it hides very quickly.

I'm on 0.3.0 and macOS 10.13.2.

**Comment by jariz** [comment]
Hiya, you can do this by simply going to your notification settings in the system preferences.
See screenshot.

![screen shot 2017-12-22 at 12 56 51](https://user-images.githubusercontent.com/1415847/34297293-a8a2523e-e717-11e7-9d89-ee9c89629a4c.png)
