### ISSUE TITLE
Constantly having to reauthenticate

### ISSUE THREAD

**Issue by zamoragreen** [jariz/Noti#70]
Since Noti updated just a few days ago (maybe a week ago, not entirely sure when that update came), I have had to reauthenticate Noti every single time I open my Macbook. Even if I didn't turn my Macbook off, even putting it to sleep causes Noti to disconnect.

**Comment by krzysztof-miemiec** [comment]
I also have this issue, this happens only when Noti disconnects while running. When I restart the app, it automatically reconnects by itself.

**Comment by jariz** [comment]
Duplicate #35
