### ISSUE TITLE
Not secure 

### ISSUE THREAD

**Issue by gone-phishing** [jariz/Noti#72]
Why is there no OAuth2 implementation :/

**Comment by jariz** [comment]
Mind being a bit more descriptive?
We're using PB's oAuth urls.

If you're talking about #44 then yes, we're aware of this 'problem'.

**Comment by gone-phishing** [comment]
Yes, its the same problem as #44 
I guess you are not understanding the severity of the 'problem'.  Not okay with me so I'll pass for now.

**Comment by jariz** [comment]
👋
