### ISSUE TITLE
Add setting to make notifications sticky until clicked

### ISSUE THREAD

**Issue by davidneedham** [jariz/Noti#79]
Notifications pop up and disappear before I have a chance to see them. It would be really nice if there was a setting to make notifications sticky so that they have to be clicked before they go away.

**Comment by jariz** [comment]
Hiya, you can do this by changing the notification setting from 'stroke' to 'alerts', as seen in this screenshot (apologies for the dutch stuff):

![schermafbeelding 2018-04-25 om 16 06 43](https://user-images.githubusercontent.com/1415847/39251099-c1529b30-48a2-11e8-8a4a-d14c375a00ce.png)

**Comment by davidneedham** [comment]
Thank you!
