### ISSUE TITLE
I can't authenticate

### ISSUE THREAD

**Issue by codeagencybe** [jariz/Noti#85]
Just installed Noti

I click authenticate me, it opens a popup, completely blank and nothing happens or is loading. 
What is going on? 

Why doesn't it load the default web browser? I can't see what's happening, so I can't even get past this point as of now. 
Some clearance how to fix this is very welcome.

**Comment by jariz** [comment]
> I click authenticate me, it opens a popup, completely blank and nothing happens or is loading.

Not sure how I can help you without you providing some more information on your specific environment, as it's working for me still.
Do you have any firewalls enabled? Proxies? VPN's?
Does the pushbullet chrome extension work?

>Why doesn't it load the default web browser

We've had this request for a while (#44), I'm just personally not interested in implementing it, but PR's are open.
Also, I'd like to kindly remind you that this is a opensource project, and not a customer help desk.
