### ISSUE TITLE
Noti is getting close when i click on notification in mac os

### ISSUE THREAD

**Issue by dillibk777** [jariz/Noti#93]
i tried getting logs in console.app but nothing shows up there related to noti error, once noti is close it automatically restarts in a minute or two.

**Comment by srujanb** [comment]
Same, to add details, while testing notifications from the Pushbullet's "Send a test notification", the app **does not** crash if I click on the `dismiss` button but it **does** crash if I click on the `done` button.

**Comment by x-f** [comment]
I have the same issue - Noti disappears if I interact with the notification.
macOS 10.15.7
Noti 0.3.2

Noti.log shows nothing when Noti.app exits:
```
09-11-2020 20:03:17 DEBUG websocketDidReceiveMessage():334 - TICKLE -> push
09-11-2020 20:03:34 DEBUG websocketDidReceiveMessage():358 - PUSH -> dismiss
09-11-2020 20:03:36 DEBUG websocketDidReceiveMessage():353 - PUSH -> mirror
09-11-2020 20:05:03 DEBUG initCrypt():77 - Encryption not enabled
09-11-2020 20:05:03 DEBUG init():41 - Init Noti
09-11-2020 20:05:03 DEBUG getUserInfo():98 - Getting user info...
09-11-2020 20:05:04 DEBUG connect():271 - Connecting to Pushbullet
09-11-2020 20:05:04 DEBUG websocketDidConnect():287 - PushManager is connected
```

However I got this line in the system.log:
```
Nov  9 20:03:40 mbp com.apple.xpc.launchd[1] (io.jari.Noti.12808[16488]): Service exited due to SIGILL | sent by exc handler[16488]
```

**Comment by ABeltramo** [comment]
Duplicated of https://github.com/jariz/Noti/issues/88
