### ISSUE TITLE
Noti can't connect behind proxy

### ISSUE THREAD

**Issue by vveloso** [jariz/Noti#95]
Hi!

When using a VPN with a corporate proxy on the other end, Noti fails to connect with the message "The operation couldn't be completed. kCFErrorDomainCFNetwork error 2."

It's true that there's a similar open issue (#24) but that one refers to a closed PR (#202) because there was some major refactoring in the meantime.

So this report looks relevant.

**Comment by jariz** [comment]
Thanks for your report, but I don't really agree on it needing a separate issue, it's still the same issue, the PR in the library just got merged in the meantime, which should mean that all we need to do is update the dependency to the latest version.
So thanks for bringing that to my attention.
