### ISSUE TITLE
Auto hide notification after 5 seconds

### ISSUE THREAD

**Issue by srjlulla** [jariz/Noti#97]
It will be very helpful if the notification is hidden after 4-5 seconds, instead of clicking Dismiss.

**Comment by jariz** [comment]
Go to system preferences and notifications.
Select Noti, and change the notification style from banner to stroke (or vice versa, can't really remember which is which)

**Comment by srjlulla** [comment]
Yes it's working Jariz. Changed from "Alerts" to "Banners".

Thanks a ton! Noti is a game-changer
